### PR TITLE
Libraries: should add all new layer IDs for expanded graphic asset.

### LINKED ISSUE #1944: CC Lib: dragging asset with Opt/Alt key to place expanded layers results in error
new doc, load a library that has an asset that contains multiple layers, drag + alt/opt onto canvas
Result: ```Action layers.addLayers failed: Error: Replacing a layer but the new layer's index seems out of bounds
    at Record.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/src/js/models/layerstructure.js:814:27)
    at Array.reduce (native)
    at Record.LayerStructure.addLayers (file:///Users/crolfs/playground-repos/spaces-design/src/js/models/layerstructure.js:796:41)
    at Fluxxor.createStore._handleLayerAdd (file:///Users/crolfs/playground-repos/spaces-design/src/js/stores/document.js:256:46)
    at Store.__handleAction__ (file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:592:16)
    at null.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:157:41)
    at file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:2465:20
    at file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:4227:12
    at baseForOwn (file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:2634:11)
    at file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:2658:13
    at Dispatcher.doDispatchLoop (file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:140:4)
    at Dispatcher.dispatch (file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:129:11)
    at Object.dispatchBinder.dispatch (file:///Users/crolfs/playground-repos/spaces-design/bower_components/fluxxor/build/fluxxor.js:269:21)
    at Object.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/src/js/actions/layers.js:301:22)
From previous event:
    at Object.addLayers (file:///Users/crolfs/playground-repos/spaces-design/src/js/actions/layers.js:292:14)
    at FluxController._applyAction (file:///Users/crolfs/playground-repos/spaces-design/src/js/fluxcontroller.js:304:36)
    at null.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/src/js/fluxcontroller.js:399:37)
From previous event:
    at null.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/src/js/fluxcontroller.js:395:22)
    at AsyncDependencyQueue._processNext (file:///Users/crolfs/playground-repos/spaces-design/src/js/util/async-dependency-queue.js:292:27)
    at null.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/src/js/util/async-dependency-queue.js:304:26)
From previous event:
    at AsyncDependencyQueue._processNext (file:///Users/crolfs/playground-repos/spaces-design/src/js/util/async-dependency-queue.js:300:21)
    at AsyncDependencyQueue.push (file:///Users/crolfs/playground-repos/spaces-design/src/js/util/async-dependency-queue.js:144:14)
    at Object.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/src/js/fluxcontroller.js:378:42)
    at eval (file://./js/jsx/Scrim.jsx:335:36)
From previous event:
    at Object.handleDropGraphic [as onDrop] (file://./js/jsx/Scrim.jsx:334:27)
    at Fluxxor.createStore.stopDrag (file:///Users/crolfs/playground-repos/spaces-design/src/js/stores/draganddrop.js:204:22)
    at React.createClass._handleDragFinish (file://./js/jsx/shared/Draggable.jsx:280:53)```

### PR DESCRIPTION
**Pull request by shaoshing**
This PR fixes #1944 (CC Lib: dragging asset with Opt/Alt key to place expanded layers results in error)

### CODE REVIEW

File: src/js/actions/libraries.js [hunk 1]
```diff
@@ -354,13 +355,19 @@ define(function (require, exports) {
                     return descriptor.playObject(placeObj);
                 })
                 .then(function () {
-                    // Standard PS will auto select the newly placed layer. This gives us the opportunity 
-                    // to get the new layer ID by getting the "layerID" property of the currently selected layer. 
-                    return descriptor.getProperty("layer", "layerID");
+                    return this.flux.actions.layers._getLayerIDsForDocumentID(currentDocument.id);
```
Comment (volfied) [inline src/js/actions/libraries.js]: You definitely want to transfer here instead of enqueueing this action. In this case, you were lucky that we didn't get a dead lock from locks, but returning an enqueue is a bad idea.

File: src/js/actions/libraries.js [hunk 2]
```diff
@@ -354,13 +355,19 @@ define(function (require, exports) {
...
+                    var nextLayerIDs = nextDocumentIDS.layerIDs,
+                        existingLayerIDs = currentDocument.layers.index.toArray();
+                        
+                    return _.difference(nextLayerIDs, existingLayerIDs).reverse();
                 })
-                .then(function (newLayerID) {
-                    // Update the current document with the new layer id.
-                    this.flux.actions.layers.addLayers(currentDocument, newLayerID);
+                .then(function (newLayerIDs) {
+                    this.flux.actions.layers.addLayers(currentDocument, newLayerIDs, true, false);
```
Comment (volfied) [inline src/js/actions/libraries.js]: Ditto

**Comment by volfied** [comment]
This is a good intermediate step, but we should instead get IDs back from Photoshop when layers are placed so we don't have to get all the layer IDs.

Needs rebase and have couple things to address. Then we should have a Core issue for the IDs coming back so we avoid calling getDocumentLayerIDs

**Comment by shaoshing** [comment]
Thanks for reviewing @volfied , Good to learn about the use of transfer in actions. I also added your note in the code. Back to you now.

**Comment by volfied** [comment]
:+1:
